### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [zathras/JRPN_Android#9] opened 2021-03-05 10:55 UTC
https://f-droid.org/wiki/index.php?title=com.jovial.jrpn/lastbuild_8&oldid=288312

**Comment by zathras** [comment] 2021-03-05 18:28
Fixed in release 1.1.4.1

**Closed by zathras** 2021-03-05 18:28 UTC

**Comment by linsui** [comment] 2021-03-27 08:45
You forget to update the version name in the build.gradle so F-Droid didn't found this version.

**Comment by zathras** [comment] 2021-03-27 14:20
I don't understand.   I changed app/build.gradle's versionName from
    1.1.3 to 1.1.4 on February 25 -- see
https://github.com/zathras/JRPN_Android/commit/64faca82906a4ed1f845c726d999be1cb852bd8d#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9
    
    The other build.gradle file doesn't have a version name property
    (https://github.com/zathras/JRPN_Android/blob/master/build.gradle).
    
    What am I missing?
    
    On 3/27/21 1:45 AM, linsui wrote:
    
    
      
      You forget to update the version name in the build.gradle so
        F-Droid didn't found this version.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zathras/JRPN_Android/issues/9#issuecomment-808693220",
"url": "https://github.com/zathras/JRPN_Android/issues/9#issuecomment-808693220",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by linsui** [comment] 2021-03-27 14:25
The problem is that you publish 1.1.4 in tag 1.1.4.1 so they mismatch... So please bump version to 1.1.4.1 and retag it or bump version to 1.1.4.2 and add a new tag.

**Comment by zathras** [comment] 2021-03-27 14:31
Oh, OK.  Done - I made it 1.1.4.2.
    
    On 3/27/21 7:25 AM, linsui wrote:
    
    
      
      The problem is that you publish 1.1.4 in tag 1.1.4.1 so they
        mismatch... So please bump version to 1.1.4.1 and retag it or
        bump version to 1.1.4.2 and add a new tag.
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zathras/JRPN_Android/issues/9#issuecomment-808741141",
"url": "https://github.com/zathras/JRPN_Android/issues/9#issuecomment-808741141",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by linsui** [comment] 2021-03-27 14:34
Thanks!
